import Head from "next/head";
import React from "react";

type Props = {
  title?: string;
};

const PageMeta = ({ title = "Flashback Web" }: Props) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default PageMeta;
